name: "AniDB-Cn"
guid: "a2b2a7ed-c4da-5120-0917-767bc0062ea3"
imageUrl: https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anidb.png
version: "5"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "jellyfin"
overview: "AniDB metadata provider"
description: >
  AniDB metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AniDB.dll"
changelog: |2-
  ### Code or Repo Maintenance ###
  - 10.8 support (#13) @crobibero
