name: "AniDB Cn"
guid: "27e60aa6-ca4f-0d5c-7cc6-98e7e142c446"
imageUrl: https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anidb.png
version: "4.0.1"
targetAbi: "10.7.7.0"
framework: "net5.0"
owner: "john123"
overview: "AniDB metadata provider"
description: >
  AniDB metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AniDB.dll"
changelog: |2-
  ### Dependency updates ###
  - chore(deps): bump release-drafter/release-drafter from v5.14.0 to v5.15.0 (#8) @dependabot

  ### CI & build changes ###
  - Update ci (#10) @h1dden-da3m0n

  ### Code or Repo Maintenance ###
  - chore: plugin images (#9) @h1dden-da3m0n
