name: Build Plugin

on:
  push:
    branches: [v4]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [v4]
    paths-ignore:
      - "**/*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release  --no-restore
        id: jprm

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          retention-days: 30
          if-no-files-found: error
          path: Jellyfin.Plugin.AniDB/bin/**
